system:
  name: "AlarmPaw"
  host: "0.0.0.0"
  port: "8080"
  mode: "debug"
  dbType: "default"
  dbPath: "./data"

mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"

apple:
    keyId: "BNY5GUGV38"
    teamId: "FUWV6U942Q"
    topic: "com.twown.bark"
    key: |-
      -----BEGIN PRIVATE KEY-----
      MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvjopbchDpzJNojnc
      o7ErdZQFZM7Qxho6m61gqZuGVRigCgYIKoZIzj0DAQehRANCAAQ8ReU0fBNg+sA+
      ZdDf3w+8FRQxFBKSD/Opt7n3tmtnmnl9Vrtw/nUXX4ldasxA2gErXR4YbEL9Z+uJ
      REJP/5bp
      -----END PRIVATE KEY-----

