version: '3'

services:
  AlarmPawServer:
    image: thurmantsao/alarm-paw-server:v2.7
    container_name: AlarmPawServer
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./deploy:/deploy

